java_library(
  name = 'roadmap',
  srcs = glob(['*.java']),
  deps = [
    '//src/net/digihippo/cryptnet/compat:compat',
    '//src/net/digihippo/cryptnet/lang:lang',
    '//src/net/digihippo/cryptnet/json:json',
  ],
  visibility = [ 'PUBLIC' ],
)