java_library(
  name = 'server',
  srcs = glob(['*.java']),
  deps = [
    '//:netty-buffer',
    '//:netty-codec',
    '//:netty-common',
    '//:netty-resolver',
    '//:netty-transport',
    '//src/net/digihippo/cryptnet/model:model',
    '//src/net/digihippo/cryptnet/roadmap:roadmap',
  ],
  visibility = [ 'PUBLIC' ]
)

java_binary(
  name = 'espionage-server',
  deps = [
    ':server'
  ],
  main_class = 'net.digihippo.cryptnet.server.NettyServer'
)