java_library(
  name = 'server',
  srcs = glob(['*.java']),
  deps = [
    '//src/net/digihippo/cryptnet/roadmap:roadmap',
    '//src/net/digihippo/cryptnet/dimtwo:dimtwo',
    '//src/net/digihippo/cryptnet/model:model',
  ],
  visibility = [ 'PUBLIC' ]
)