java_library(
  name = 'model',
  srcs = glob(['*.java']),
  deps = [
    '//src/net/digihippo/cryptnet/roadmap:roadmap',
    '//src/net/digihippo/cryptnet/dimtwo:dimtwo',

    '//:jackson',
  ],
  visibility = [ 'PUBLIC' ],
)