java_library(
  name = 'cryptnet',
  srcs = glob(['*.java']),
  deps = [
    '//src/net/digihippo/cryptnet/model:model',
    '//src/net/digihippo/cryptnet/roadmap:roadmap',

    '//src/net/digihippo/cryptnet/server:server',
  ],
  visibility = [ 'PUBLIC' ],
)