java_test(
  name = 'model',
  srcs = glob(['*.java']),
  deps = [
    '//src/net/digihippo/cryptnet/model:model',
    '//src/net/digihippo/cryptnet/dimtwo:dimtwo',
    '//:hamcrest',
    '//:jackson',
    '//:junit',
  ],
  visibility = [ 'PUBLIC' ],
)